name: Update weather badge

on:
  workflow_dispatch:

  schedule:
    # Toutes les 2 heures environ
    # Horaires en UTC
    - cron: "11 */2 * * *"

permissions:
  contents: write

concurrency:
  group: update-weather-badge
  cancel-in-progress: false

jobs:
  update-weather-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update weather badge
        run: python scripts/update_weather_badge.py

      - name: Commit weather badge if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet docs/meteo-f4maj.svg; then
            echo "No weather badge change."
          else
            git add docs/meteo-f4maj.svg
            git commit -m "Update weather badge"
            git push
          fi
